### ISSUE TITLE
Chromium Video Issue

### ISSUE THREAD

**Issue by nxvipin** [nitcalicut/Paathshaala#18]
Videos cannot be played on Chromium. Tested on Chromium 14.0.835.163 (Developer Build 101024 Linux) Built on Debian unstable, running on Debian wheezy/sid

**Comment by jaseemabid** [comment]
Works well in `15.0.874.106 (Developer Build 107270 Linux) Ubuntu 10.04`. Cant do much on this. I think we can forget about this one.
