### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by jaseemabid** [nitcalicut/Paathshaala#19]
Need a uniform and standard way of form validation. 
jQuery plugins which can do all the required tasks is fine or custom codes required. 
Currently needed for join and new video submission.

**Comment by nxvipin** [comment]
Try Jquery validation. Modify it if it does not satisfy our requirements :)

## 

Regards,
Vipin Nair,
National Institute of Technology, Calicut
http://gplus.to/swvist

**Comment by jaseemabid** [comment]
I haven't explored it much. Will do it soon.
We need regular expression check for some fields like roll numbers, ajax check for username and both for emails to see if it has been already taken. A bit complicated task.

**Comment by jaseemabid** [comment]
Hard coded both validation functions.
validateVideo() @ SHA : df8416a41a80001cbe2761040ae1304104737242 
validateJoin() @ SHA : 50bacfb3953f833e2b0d2f8ee3ee2c9cb79e434c
