### ISSUE TITLE
Content duplication in 3 sections of home page

### ISSUE THREAD

**Issue by jaseemabid** [nitcalicut/Paathshaala#22]
Same content repeated in featured, toprated and popular sections. 
this gives a feeling that we have only 4 videos in the repo. BAD !

**Comment by nxvipin** [comment]
Content duplication check is resource intensive. Request to each section will require a minimum of three queries to identify and eliminate duplicates. I suggest we combine all three section into one JSON to minimize the number of queries and to speed up the system.

**Comment by nxvipin** [comment]
A new branch "combined-storybox-json" is created which combines all the three JSON's and eliminates any duplicate content from all the three sections in the front page. Check json/storybox.json.php to see JSON structure. Front end code needs to be modified to utilize the new JSON structure. Issue assigned to @jaseemabid

**Comment by jaseemabid** [comment]
Lesser calls to server. This should definitely be faster. I'm a bit busy now, but i will get this done. Will notify before any branch merges.

**Comment by jaseemabid** [comment]
Done !
Check SHA : a58d21963bf9d49f6aca2f0285c96cfd17e316dc
Home page call updated. Only 1 ajax request for the whole page now. Better performance.
UI generation code rewritten, I think it improved. Some level of error checks with try ... catch blocks.
Merging "combined-storybox-json" to "dev" will lead to quite a lot of conflicts. We can do it today evening and once  "combined-storybox-json" merged to dev, we can close this issue.
