### ISSUE TITLE
video.json.php Returning wrong information

### ISSUE THREAD

**Issue by jaseemabid** [nitcalicut/Paathshaala#25]
Accessing '/json/video.json.php?video=...' with an invalid video id is returning wrong info.
Eg : 

For cid 1900, It returns 

```
{
    cid: "1900",
    title: null,
    desc: null,
    tags: [ ],
    timestamp: null,
    viewcount: null,
    status: null,
    path: "//1900.ogv",
    poster: "/thumbs/1900.png",
    likestatus: 0,
    sid: null,
    sname: null,
    order: null,
    uid: null,
    uname: null
}
```

It should have been ideally null in every field.

**Comment by nxvipin** [comment]
Fixed. All fields in JSON will be NULL if the content is not present.
Commit: fe334babcd

**Comment by jaseemabid** [comment]
Works fine :)
