### ISSUE TITLE
Sessions failing

### ISSUE THREAD

**Issue by jaseemabid** [nitcalicut/Paathshaala#6]
Unable to login sometimes, sessions failing without any error messages.

**Comment by jaseemabid** [comment]
Issue fixed

**Comment by jaseemabid** [comment]
Need response. For eg, if it failed because of wrong password, it should be reported back.

**Comment by jaseemabid** [comment]
@swvist Since we are reloading the page, we wont be able to send a response on failed login via ajax. Resend the user to the same page with an additional get variable to fix the issue.

**Comment by jaseemabid** [comment]
We can make this ajax based if required. Reload on success with logged in ui. Need to display more sensible error messages than a Boolean success/fail, which the user will understand without we even telling it. This is I believe the 3rd time we are having trouble with sessions.

**Comment by nxvipin** [comment]
DB Issue. Fixed :)
